spring.application.name=tuition-platform
security.jwt.secret-key=4cf850125c09e143d8aab1283e52210727c3e5fe13e87af20960f34e65e24c1a
security.jwt.expiration-time=3600000

# -------------------------
# Datasource (PostgreSQL)
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/tuition_db
spring.datasource.username=tuition_admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------
# JPA / Hibernate
# -------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------
# Connection Pool (HikariCP)
# -------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool

# -------------------------
# Server Configuration
# -------------------------
server.port=8080

# -------------------------
# Optional: Logging
# -------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE